trigger:
  - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  - group: GoldenImageSecret
  - name: azureSubscription
    value: 'PALO IT Azure Subscription'
  - name: resourceGroupName
    value: 'golden-image-rg'

steps:
- script: echo '##vso[task.setvariable variable=uniqueId]golden-img-$(Build.SourceVersion)'
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: $(azureSubscription)
    action: Create Or Update Resource Group
    resourceGroupName: $(resourceGroupName)
    deploymentName: CreateGoldenImage
    location: eastasia
    templateLocation: Linked artifact
    csmFile: src/template.json
    csmParametersFile: src/parameters.json
    overrideParameters: -adminPassword "$(secretAdminPassword)" -networkInterfaceName "$(uniqueId)-nif" -networkSecurityGroupName "$(uniqueId)-nsg" -virtualNetworkName "$(uniqueId)-vnet" -publicIpAddressName "$(uniqueId)-ip" -virtualMachineName "$(uniqueId)" -virtualMachineRG "$(resourceGroupName)"
    deploymentMode: incremental
