trigger:
  - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  azureSubscription: '2df4b63b-fc82-4d28-9ebd-5169d2f46507'
  resourceGroupName: 'azure-golden-image-rg'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: $(azureSubscription)
    action: Create Or Update Resource Group
    resourceGroupName: $(resourceGroupName)
    deploymentName: Create Golden Image
    location: eastasia
    templateLocation: Linked artifact
    csmFile: src/template.json
    csmParametersFile: src/parameters.json
    overrideParameters: -adminPassword "$(secretAdminPassword)"
    deploymentMode: complete
